### ISSUE TITLE
[Warn] ❗️ Please keep the original author and address

### ISSUE THREAD

**Issue by Harry-zklcdc** [chokiproai/AI-Copilot-EN#2]
## **According to the MIT agreement, the original author information needs to be retained.**

**Comment by chokiproai** [comment]
I'm sorry I forgot to credit the original author 😓😿😿😿😭😭😭😭

**Comment by chokiproai** [comment]
Thank you for the reminder

**Comment by chokiproai** [comment]
Sorry Harry-zklcdc, this is my mistake for not including the original author According to the MIT agreement

**Comment by chokiproai** [comment]
Your API has a problem: it only works for a while and then falls into a state of waiting for a response

**Comment by chokiproai** [comment]
> Your API has a problem: it only works for a while and then falls into a state of waiting for a response

![image](https://github.com/chokiproai/AI-Copilot-EN/assets/128912789/84e58c44-36fb-4c63-bfbe-702316475b96)

**Comment by chokiproai** [comment]
Harry-zklcdc have you read it yet?

**Comment by chokiproai** [comment]
https://github.com/chokiproai/AI-Copilot-EN/commit/4453b346f40aa122cfd431b777c5a9a2b97e375f

**Comment by chokiproai** [comment]
# ❤️ Harry zklcdc
I'm really sorry for making you feel uncomfortable. You can forgive me ❤️

**Comment by Harry-zklcdc** [comment]
Fork my repository. And keep my commit history. 

And keep the origin author: https://github.com/adams549659584/go-proxy-bingai

Keep original link: https://github.com/chokiproai/AI-Copilot-EN/blob/4453b346f40aa122cfd431b777c5a9a2b97e375f/frontend/src/components/ChatNav/ChatNav.vue#L384-L405

**Comment by chokiproai** [comment]
❤️

**Comment by chokiproai** [comment]
I think just leave your source code and everyone will know the original author via forked from

**Comment by chokiproai** [comment]
https://github.com/chokiproai/AI-Copilot-EN/commit/b8d19f49818c97411ff40bf330106dcc908cad6d
