### ISSUE TITLE
make it api like gpt4api

### ISSUE THREAD

**Issue by hebijush** [chokiproai/AI-Copilot-EN#3]
### Describe the problem related to the feature request

so we can use in any project

### Describe the solution you'd like

so i can use in tg bot

**Comment by chokiproai** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI

**Comment by chokiproai** [comment]
https://github-com.translate.goog/Harry-zklcdc/go-proxy-bingai/wiki/BingAPI?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=vi&_x_tr_pto=wapp

**Comment by chokiproai** [comment]
![image](https://github.com/chokiproai/AI-Copilot-EN/assets/128912789/97c6bead-6af5-42be-b8eb-03903293d74d)

**Comment by chokiproai** [comment]
https://....../v1/chat/completions

**Comment by chokiproai** [comment]
Environment variables:
> APIKEY: options as you like

**Comment by chokiproai** [comment]
See details at: https://github.com/Harry-zklcdc/go-proxy-bingai/wiki

**Comment by hebijush** [comment]
i used your api https://ngoctuanai-copiloten.hf.space/v1/chat/completions . and key 'free' but it says Error: OpenAI API Error
> Not Found   and after using https://ngoctuanai-copiloten.hf.space/v1/  Error: OpenAI API Error
> Method Not Allowed

**Comment by chokiproai** [comment]
I don't offer it to everyone

**Comment by chokiproai** [comment]
Please deploy your own space: https://github.com/chokiproai/AI-Copilot-EN?tab=readme-ov-file#-hugging-face

**Comment by hebijush** [comment]
thanks a lot for helping . can you please translate ui to english? many people dont know vietnamese.

**Comment by chokiproai** [comment]
This UI is in English

**Comment by hebijush** [comment]
sir , can you host a api site for replacing openai api , where i will use my key and give access to others . so they can use api inderectly using my api?(i dont wanna share original key)

**Comment by chokiproai** [comment]
using [One API](https://github.com/songquanpeng/one-api)

**Comment by hebijush** [comment]
can you please host it in huggingface/free ?

**Comment by chokiproai** [comment]
> can you please host it in huggingface/free ?

- Hugging face has blocked queries to use the API
- Please use vps or other services
